# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210712_1456'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
