# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210712_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, verbose_name='bio'),
        ),
    ]
